Repository acm-ucr/iranian-student-association-website, pull requests merged in 2024-11, with the labels that each got.

#39 Implemented Title on each page
  package-lock.json
  package.json
  public/culture/Culture.svg
  public/gallery/Gallery.svg
  public/mission/MissionStatement.svg
  src/app/culture/page.tsx
  src/app/gallery/page.tsx
  src/app/mission/page.tsx
  src/components/Title.tsx
Labels: ready for review

#54 Update philanthropy page to include current organization
  public/philanthropy/ISCC.svg
  src/components/philanthropy/page.tsx
Labels: in progress

#59 updated mission statement title
  public/mission/updatedmissiontitle.svg
  src/app/mission/page.tsx
Labels: ready for review

#52 Footer Response
  src/components/footer.tsx
Labels: in progress, ready for review

#51 Gallery Response
  package-lock.json
  src/app/gallery/page.tsx
  src/components/gallery/background.tsx
  src/components/gallery/buttonLayout.tsx
  src/components/gallery/buttons.tsx
Labels: ready for review

#37 Implement calendar
  src/app/join-us/page.tsx
  src/app/layout.tsx
  src/components/join-us/Events.tsx
  src/components/join-us/WrappedEvents.tsx
  src/components/join-us/background.tsx
  src/components/join-us/calendar.tsx
  src/components/join-us/calendar/Calendar.tsx
  src/components/join-us/calendar/CustomEvents.tsx
  src/components/join-us/calendar/CustomHeader.tsx
  src/components/join-us/calendar/CustomToolbar.tsx
  src/components/join-us/calendar/Modal.tsx
  src/components/join-us/socials.tsx
  tailwind.config.ts
Labels: in progress, ready for review

#62 Implement gallery component + socials page
  public/gallery/cultural-events/charmander.webp
  public/gallery/cultural-events/culturalTitle.svg
  public/gallery/fundraisers/fundraisersTitle.svg
  public/gallery/socials/bg1.svg
  public/gallery/socials/bg2.svg
  public/gallery/socials/socialTitle.svg
  public/gallery/socials/socials1.webp
  public/gallery/socials/socials2.webp
  public/gallery/socials/socials3.webp
  public/gallery/socials/socials4.webp
  public/gallery/socials/socials5.webp
  public/gallery/socials/socials6.webp
  public/gallery/socials/socials7.webp
  public/gallery/socials/socials8.webp
  public/gallery/socials/socials9.webp
  public/gallery/tabling/tablingTitle.svg
  src/app/gallery/[type]/page.tsx
  src/app/gallery/page.tsx
  src/components/gallery/GalleryImage.tsx
  src/components/gallery/GalleryImages.tsx
  src/components/gallery/buttonLayout.tsx
  src/components/gallery/buttons.tsx
  src/components/mission/page.tsx
  src/data/gallery/Pictures.ts
  tailwind.config.ts
Labels: ready for review

#55 Zwang0987/nav bar response
  src/components/navigation.tsx
Labels: in progress, ready for review

#66 Tabling Gallery
  public/gallery/tabling/tabling1.webp
  public/gallery/tabling/tabling2.webp
  src/data/gallery/Pictures.ts
Labels: in progress, ready for review

#53 Update Titles
  public/join-us/JoinUs.svg
  src/app/join-us/page.tsx
  src/components/join-us/background.tsx
  src/components/join-us/title.tsx
  src/components/landing/landingtext.tsx
Labels: in progress, ready for review

#65 Fundraiser Gallery
  public/gallery/fundraisers/fundraiser1.webp
  public/gallery/fundraisers/fundraiser2.webp
  public/gallery/fundraisers/fundraiser3.webp
  src/data/gallery/Pictures.ts
Labels: in progress

#79 Added Fade in and fade out for the culture page
  package-lock.json
  package.json
  src/components/culture/text.tsx
Labels: in progress, ready for review

#77 Mission Response
  package-lock.json
  src/app/mission/page.tsx
  src/components/mission/page.tsx
Labels: ready for review
