Repository acm-ucr/iranian-student-association-website, pull requests merged in 2024-10, with the labels that each got.

#19 Created nav bar
  pnpm-lock.yaml
  public/favicon.ico
  public/home/ucr.webp
  public/logo.webp
  public/mission/group.svg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/navigation.tsx
  src/data/nav.ts
  src/public/gallery/test.txt
  tailwind.config.ts
Labels: ready for review

#20 footer .tsx
  package-lock.json
  package.json
  src/app/join-us/page.tsx
  src/app/layout.tsx
  src/components/footer.tsx
  src/data/Group 400.svg
  src/data/footer-bg-cropped7.svg
  src/utils/footer.ts
Labels: enhancement

#28 Join us: Calendar Rough Draft + Paisleys + Socials
  pnpm-lock.yaml
  public/join-us/groupme.svg
  public/join-us/paisley1.webp
  public/join-us/paisley2.webp
  src/app/join-us/page.tsx
  src/components/join us/calendar.tsx
  src/components/join us/links.tsx
  src/components/join-us/background.tsx
  src/components/join-us/calendar.tsx
  src/components/join-us/links.tsx
  src/components/join-us/socials.tsx
  src/data/icons.ts
Labels: in progress, ready for review

#25 Philanthropy Page
  public/philanthropy/IAWF.svg
  public/philanthropy/childrenInternational.svg
  public/philanthropy/handshake.svg
  public/philanthropy/ourPhilanthropy.svg
  src/app/philanthropy/page.tsx
  src/components/button.tsx
  src/components/philanthropy/page.tsx
Labels: ready for review

#29 Dennyhly/gallery button
  public/gallery/paisley1.svg
  public/gallery/paisley2.svg
  src/app/gallery/page.tsx
  src/components/gallery/background.tsx
  src/components/gallery/buttonLayout.tsx
  src/components/gallery/buttons.tsx
  src/data/gallery/Titles.ts
  tailwind.config.ts
Labels: ready for review

#32 Culture Paisleys
  public/culture/paisley1.svg
  public/culture/paisley2.svg
  src/app/culture/page.tsx
  src/components/culture/background.tsx
Labels: ready for review

#23 button component
  src/components/button.tsx
  src/components/philanthropy/page.tsx
Labels: in progress, ready for review

#38 Update links
  src/components/footer.tsx
  src/components/join-us/socials.tsx
  src/data/icons.ts
  src/utils/footer.ts
Labels: ready for review

#24 Zwang0987/mission page pull request
  src/app/mission/page.tsx
  src/components/mission/page.tsx
Labels: in progress
